FINALTECH_GEARWHEEL:
  1:
    id: POLISHED_GRANITE
  2:
    id: POLISHED_GRANITE
  3:
    id: POLISHED_GRANITE
  4:
    id: POLISHED_DIORITE
  5:
    id: POLISHED_DIORITE
  6:
    id: POLISHED_DIORITE
  7:
    id: POLISHED_ANDESITE
  8:
    id: POLISHED_ANDESITE
  9:
    id: POLISHED_ANDESITE